### ISSUE TITLE
how to get chr20.PEI.Enhancer.data.test.txt

### ISSUE THREAD

**Issue by usernicai** [JiamanZhang/Lab_Annotate_Enhancer_type#1]
Hi,how to get the chr20.PEI.Enhancer.data.test.txt,given the loop bedPE file,
since i just want to extract the EPC info from the loop file

**Comment by JiamanZhang** [comment]
Hi，this article (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8397779/) may be help you.
